{% set name = "pygeofilter" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pygeofilter-{{ version }}.tar.gz
  sha256: f92bc0622099f87fe8b36de7abdd86059d615a89ed60822737082223a578e150

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - setuptools >=46.4
    - pip
  run:
    - python >=3.7
    - dateparser
    - lark
    - pygeoif >=1.0.0
    - dataclasses

test:
  imports:
    - pygeofilter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/geopython/pygeofilter
  summary: pygeofilter is a pure Python parser implementation of OGC filtering standards
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
