{% set name = "pygeofilter" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pygeofilter-{{ version }}.tar.gz
  sha256: 265a0a5d47e8421b7f07710d66422e94c4ee2590ce3fad6bd4b61a248e4e816b

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=46.4
    - pip
  run:
    - python >={{ python_min }}
    - dateparser
    - lark <1.0
    - pygeoif >=1.0.0
    - dataclasses

test:
  imports:
    - pygeofilter
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/geopython/pygeofilter
  summary: pygeofilter is a pure Python parser implementation of OGC filtering standards
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
