{% set name = "pygeofilter" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pygeofilter-{{ version }}.tar.gz
  sha256: cbb4a5f14af0b87e4f0c0c81c659ff64e44351c98e9f61d36af515d896fa8a05

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=46.4
    - pip
  run:
    - click
    - python >={{ python_min }}
    - dateparser
    - lark
    - pygeoif >=1.0.0
    - dataclasses

test:
  imports:
    - pygeofilter
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/geopython/pygeofilter
  summary: pygeofilter is a pure Python parser implementation of OGC filtering standards
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
